apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-pltd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-service-e2e-tenant/appstudio/dc-metro-map-pltd@sha256:e129a2f040dadef4a257493071492299c24688f8bebd5c7d0e96a9e7fcde1745
        name: my-nodejs
        resources: {}
status: {}
